name: Elixir CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Проверка кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Устанавливаем Elixir
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.14' 
          otp-version: '26'

      # Переход в нужную директорию и установка зависимостей
      - name: Install dependencies
        run: |
          cd ./cli_chat
          mix deps.get
      
       # Настройка подключения к базе данных для тестов
      - name: Set up database
        run: |
          cd ./cli_chat
          mix ecto.create
          mix ecto.migrate

      # Проверка форматирования кода
      - name: Check formatting
        run: |
          cd ./cli_chat
          mix format --check-formatted

      # Запуск тестов
      - name: Run tests
        run: |
          cd ./cli_chat
          mix test